global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/trading-alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Trading Bot Backend
  - job_name: 'trading-bot-backend'
    static_configs:
      - targets: ['backend:9464']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s

  # Nginx metrics (if nginx-prometheus-exporter is configured)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    metrics_path: /metrics

  # PostgreSQL metrics
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis metrics  
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Node metrics for container host
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: /metrics

  # Custom application metrics
  - job_name: 'trading-bot-metrics'
    static_configs:
      - targets: ['backend:3001']
    metrics_path: /api/metrics
    scrape_interval: 30s